define(function () {
  'use strict'

  return {
    CANVAS_HEIGHT: 500
    ,CANVAS_WIDTH: 300
    ,GRAVITY_ACCELERATION: 9.8 / 100
    ,BACKGROUND_COLOR: '#444'
    ,JUMPER_COLOR: '#f0f'
    ,JUMPER_HEIGHT: 25
    ,JUMPER_WIDTH: 25
    ,JUMPER_MASS: 40
    ,JUMPER_PUSH_FORCE: 8
    ,JUMPER_MAX_X_VELOCITY: 10
    ,JUMPER_ACCELERATION_X: 15
    ,JUMPER_TERMINAL_VELOCITY: 30
    ,JUMPER_MAX_JUMP_VELOCITY: 22
    ,JUMPER_JUMP_FORCE: 3
    ,KEY_SPACE: 32
    ,KEY_LEFT: 37
    ,KEY_UP: 38
    ,KEY_RIGHT: 39
    ,KEY_DOWN: 40
    ,KEY_H: 72
    ,KEY_J: 74
    ,KEY_K: 75
    ,KEY_L: 76
    ,KEY_P: 80
    ,BACKGROUND_IMAGE_URL: 'img/noise_bg.png'
    ,BACKGROUND_IMAGE_TILE_HEIGHT: 200
    ,BACKGROUND_IMAGE_TILE_WIDTH: 200
    ,VIEWPORT_BORDER_DISTANCE_PAN_THRESHOLD: 100
  }

});
